[build]
  publish = "."

[[headers]]
  for = "/app-ads.txt"
  [headers.values]
    Content-Type = "text/plain; charset=UTF-8"
    Cache-Control = "public, max-age=3600"

[[redirects]]
  from = "/app-ads"
  to = "/app-ads.txt"
  status = 301
  force = true
